# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Bruno Lui
tagline:          'Thinking loud'
description:      'This is just a place to put some of my thoughts about software development, technology and entrepreneurship. Feedbacks are welcome. =)'
url:              http://brunolui.com
avatar_url:       https://pbs.twimg.com/profile_images/489599291917602816/eKu1tdPX_400x400.jpeg

author:
  name:           'Bruno Lui'
  url:            https://twitter.com/bruno_lui

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/brunolui

disqus_short_name:  brunolui